name: implied_volatility_surface
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - QuantLib==1.40
      - pandas==2.3.3
      - numpy==2.4.0
      - scipy==1.16.3
      - plotly==6.5.0
      - streamlit==1.52.2